# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://localhost:27017"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - catalogdb

volumes:
  mongo_data: